#mybatis config
mybatis:
 typeAliasesPackage: org.ranji.lemon.model
 mapperLocations: classpath:mapper/**/*.xml
#druid datasource
spring:
 datasource:
  #base config
  name: lemonDS
  url: jdbc:mysql://localhost:3306/lemon?useUnicode=true&characterEncoding=UTF-8
  username: root
  password: 123456
  #使用druid数据源
  type: com.alibaba.druid.pool.DruidDataSource
  driver-class-name: com.mysql.jdbc.Driver
  #下面为连接池的设置，初始化大小，最小，最大值
  initialSize: 3
  minIdle: 3
  maxActive: 20
#kaptcha
kaptcha:
 border: yes
 borderColor: 105,179,90
 imageWidth: 125
 imageHeight: 45
 sessionKey: verifyCode
 textproducerFontColor: blue
 textproducerCharLength: 4
 textproducerFontNames: 宋体,楷体,微软雅黑
 